name: Release Charts

on: [push]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "Paulo Calaes"
          git config user.email "paulocalaes@gmail.com"

      - name: Add helm repo
        run: helm repo add orc8r https://paulocalaes.github.io/magma-charts-3-17-2022

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.3.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
